kind: pipeline
type: docker
name: linux-amd64 - tests,coverage, publish image

platform:
  arch: amd64
  os: linux


steps:
- name: test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  pull: always
  environment:
    JWT_SECRET:
      from_secret: jwt_secret
    TEST_DATABASE_URL:
      from_secret: test_database_url
    DATABASE_URL:
      from_secret: test_database_url
  commands:
    - cd ForkEat/
    - dotnet test --logger "console;verbosity=detailed" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

- name: coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov-token
    files:
      - ForkEat/ForkEat.Core.Tests/coverage.opencover.xml
    required: true

- name: publish image
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    repo: thomaslacaze/forkeat-server
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: ForkEat/ForkEat.Web/Dockerfile
  when:
    event:
    - push
    - tag
    branch:
    - master
    - main


---
kind: pipeline
type: docker
name: deploy readme
depends_on:
  - linux-amd64 - tests,coverage, publish image

platform:
  arch: amd64
  os: linux

steps:
- name: publish readme to Dockerhub
  image: thomaslacaze/dockerhub-description:2.4.1
  pull: always
  settings:
    repository: thomaslacaze/forkeat-server
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    readme: /drone/src/README.md

trigger:
  branch:
  - master
  - main
  event:


# ---
# kind: pipeline
# type: docker
# name: linux-arm64

# platform:
#   arch: arm64
#   os: linux

# steps:
# - name: test
#   image: mcr.microsoft.com/dotnet/sdk:6.0
#   environment:
#     JWT_SECRET:
#       from_secret: jwt_secret
#     TEST_DATABASE_URL:
#       from_secret: test_database_url
#   commands:
#     - cd ForkEat
#     - dotnet test

# - name: publish image
#   image: plugins/docker
#   settings:
#     auto_tag: true
#     auto_tag_suffix: linux-arm64
#     repo: thomaslacaze/forkeat-server
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password
#     dockerfile: ForkEat/ForkEat.Web/Dockerfile


# trigger:
#   event:
#   - tag